# Yarn configuration for dependency resolution
nodeLinker: node-modules

# Package resolution
packageExtensions:
  ajv-keywords@*:
    peerDependencies:
      ajv: ^8.0.0

# Enable yarn resolutions
enableGlobalCache: false