# Render.com deployment configuration for Backend
# This file enables one-click deployment to Render

services:
  # Backend API Service
  - type: web
    name: ledgerlink-backend
    env: node
    region: oregon
    plan: starter # Free tier
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://ledgerlink.vercel.app
      - key: FRONTEND_URL
        value: https://ledgerlink.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: XERO_CLIENT_ID
        sync: false
      - key: XERO_CLIENT_SECRET
        sync: false
      - key: XERO_REDIRECT_URI
        value: https://ledgerlink.onrender.com/api/xero/callback
    
    # Auto-deploy from main branch
    autoDeploy: true
    branch: main
    
    # Health check configuration
    healthCheck:
      path: /health
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
